### ISSUE TITLE
Low frequency device

### ISSUE THREAD

**Issue by MohammedBENHADINE** [nimaltd/ds18b20#3]
Hey,
I've used the library with same clock configuration and it was working great.
Now i'm using it with a low frequency configuration (32Mhz , no external clock) and i've problems reading from sensor ,it's always at Zero.
I've tried to change the timer counts (PRS) from 71 to 31 to stay aligned with the 1us delay but no success.
Since it's supporting FreeRTOS , could we just use the osDelay() instead of a hardware timer ?
Any solutions for my problem ?
Regards

**Comment by nimaltd** [comment]
hello. I never test below 48mhz . I think better try 32mhz with no rtos.

**Comment by MohammedBENHADINE** [comment]
Thanks for the rapid feedback.
Okey i'll try
